services:
  api:
    build: .
    environment:
      POSTGRES_CONN_STR: "postgres://anaskwa:MyPassw12s@database:5432/users?sslmode=disable"
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - .:/user-service
  
  database:
    image: postgres
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: anaskwa
      POSTGRES_PASSWORD: MyPassw12s
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data: